#config file for AMI
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: Install pip
          command: sudo curl -O https://bootstrap.pypa.io/get-pip.py && sudo python3 get-pip.py --user
      - run:
          name: Install awscli
          command: sudo pip3 install awscli --upgrade --user
      - run:
          name: Download packer
          command: |
            wget -q https://releases.hashicorp.com/packer/1.3.4/packer_1.3.4_linux_amd64.zip 
            unzip packer*.zip  
            chmod +x packer
      - run:
          name: Validate Packer Template
          command: ./packer validate amazon_ami.json
      - run:
          name: Build AMI
          command: |
            ./packer build \
            -var "aws_region=${AWS_REGION}" \
            amazon_ami.json
